import { Bot, Sparkles, Shield, Music, Zap, MessageSquare, Globe, Github, Twitter, Mail } from "lucide-react";
import prayagAvatar from "@/assets/prayag-avatar.jpg";

export const siteConfig = {
  bot: {
    name: "AstraX",
    tagline: "The next-generation Discord bot",
    description:
      "AstraX is an all-in-one Discord bot crafted for modern communities. Moderation, music, fun, utilities — beautifully designed and lightning fast.",
    version: "v3.2.0",
    servers: "120K+",
    users: "8.4M+",
    commands: 240,
    uptime: "99.99%",
    inviteUrl: "https://discord.com/oauth2/authorize?client_id=1510888413933600778",
    supportUrl: "https://discord.gg/5tQKwgKmbM",
  },

  nav: [
    { label: "Home", href: "/" },
    { label: "Commands", href: "/commands" },
    { label: "About", href: "/about" },
    { label: "Privacy", href: "/privacy" },
  ],

  features: [
    {
      icon: Shield,
      title: "Advanced Moderation",
      description: "AI-powered auto-mod, raid protection, and granular permission controls keep your server safe 24/7.",
    },
    {
      icon: Music,
      title: "High-Fidelity Music",
      description: "Crystal clear lossless audio streaming from Spotify, YouTube, SoundCloud and Apple Music.",
    },
    {
      icon: Sparkles,
      title: "Custom Embeds",
      description: "Create stunning announcements with our visual embed builder — no code required.",
    },
    {
      icon: Zap,
      title: "Lightning Fast",
      description: "Globally distributed infrastructure ensures every command responds in under 50ms.",
    },
    {
      icon: MessageSquare,
      title: "Smart Tickets",
      description: "A complete support system with transcripts, categories and staff assignments.",
    },
    {
      icon: Globe,
      title: "20+ Languages",
      description: "Fully translated experience for your international community members.",
    },
  ],

  commandCategories: [
    {
      name: "Moderation",
      commands: [
        { name: "!ban", description: "Ban a member from the server", usage: "!ban <user> [reason]" },
        { name: "!kick", description: "Kick a member from the server", usage: "!kick <user> [reason]" },
        { name: "!mute", description: "Timeout a member", usage: "!mute <user> <duration>" },
        { name: "!warn", description: "Issue a warning to a member", usage: "!warn <user> <reason>" },
        { name: "!purge", description: "Bulk delete messages", usage: "!purge <amount>" },
        { name: "!purgebots", description: "Purge only bot messages from the channel", usage: "!purgebots <amount>" },
        { name: "!hackban", description: "Ban a user who is not in the server", usage: "!hackban <user_id> [reason]" },
        { name: "!softban", description: "Ban and immediately unban a member to clear their messages", usage: "!softban <user> [reason]" },
        { name: "!unban", description: "Unban a member from the server", usage: "!unban <user_id>" },
        { name: "!unbanall", description: "Unban all banned members from the server", usage: "!unbanall" },
        { name: "!block", description: "Block a user from using specific bot channels", usage: "!block <user>" },
        { name: "!unblock", description: "Unblock a user from bot channels", usage: "!unblock <user>" },
        { name: "!unmute", description: "Remove timeout from a member", usage: "!unmute <user>" },
        { name: "!unmuteall", description: "Unmute all muted members in the voice channel", usage: "!unmuteall" },
        { name: "!muteinfo", description: "Check active timeout details for a user", usage: "!muteinfo <user>" },
        { name: "!mutereset", description: "Reset timeout status and history", usage: "!mutereset <user>" },
        { name: "!warninfo", description: "Check warnings list of a member", usage: "!warninfo <user>" },
        { name: "!warnreset", description: "Reset/Clear all warnings of a member", usage: "!warnreset <user>" },
        { name: "!modrole", description: "Configure the moderator role for the server", usage: "!modrole <role>" },
        { name: "!trusted", description: "Manage trusted users and roles (Extra Admins)", usage: "!trusted <add/remove> <user/role>" },
        { name: "!ignore", description: "Configure channels or roles for the bot to ignore", usage: "!ignore <channel/role>" },
        { name: "!media", description: "Configure media-only channels and whitelists", usage: "!media <channel>" },
        { name: "!mediachannel", description: "Set or manage media-only channels", usage: "!mediachannel <channel>" },
        { name: "!automod", description: "Manage native Discord AutoMod rules", usage: "!automod <enable/disable>" },
        { name: "!antilink", description: "Manage link protection settings", usage: "!antilink <enable/disable>" },
        { name: "!antinuke", description: "Manage AntiNuke security settings", usage: "!antinuke <enable/disable>" },
        { name: "!antispam", description: "Configure anti-spam filters", usage: "!antispam <enable/disable>" },
        { name: "!antiunverifiedbot", description: "Block unverified bots from joining", usage: "!antiunverifiedbot <enable/disable>" },
        { name: "!antiinvite", description: "Block Discord server invite links", usage: "!antiinvite <enable/disable>" },
        { name: "!antiswear", description: "Block swear words in chat", usage: "!antiswear <enable/disable>" },
        { name: "!hide", description: "Hide the current channel from members", usage: "!hide [#channel]" },
        { name: "!hideall", description: "Hide all public channels", usage: "!hideall" },
        { name: "!unhide", description: "Unhide the channel for members", usage: "!unhide [#channel]" },
        { name: "!unhideall", description: "Unhide all hidden channels", usage: "!unhideall" },
        { name: "!lock", description: "Lock the channel to prevent typing", usage: "!lock [#channel]" },
        { name: "!lockall", description: "Lock all public text channels", usage: "!lockall" },
        { name: "!unlock", description: "Unlock the channel for members to chat", usage: "!unlock [#channel]" },
        { name: "!unlockall", description: "Unlock all locked channels", usage: "!unlockall" },
        { name: "!nuke", description: "Clone and delete the current channel to wipe history", usage: "!nuke" },
        { name: "/automod", description: "Manage native Discord AutoMod rules.", usage: "/automod" },
        { name: "/antilink", description: "Manage link protection settings.", usage: "/antilink" },
        { name: "/antinuke", description: "Manage AntiNuke security settings.", usage: "/antinuke" },
        { name: "/moderation", description: "moderation commands.", usage: "/moderation" },
        { name: "/modrole", description: "Configure the moderator role for the server", usage: "/modrole" },
        { name: "/trusted", description: "Manage trusted users and roles (Extra Admins).", usage: "/trusted" }
      ],⁷
    },
    {
      name: "Music",
      commands: [
        { name: "!Play", description: "Play a song or playlist from supported platforms", usage: "!Play <query/URL>" },
        { name: "!playnow", description: "Play a song immediately, bumping it to the top of queue", usage: "!playnow <query/URL>" },
        { name: "!pause", description: "Pause the currently playing music", usage: "!pause" },
        { name: "!resume", description: "Resume the paused music track", usage: "!resume" },
        { name: "!Skip", description: "Skip the current playing track", usage: "!Skip" },
        { name: "!Previous", description: "Play the previous track from history", usage: "!Previous" },
        { name: "!Stop", description: "Stop the music player and clear the queue", usage: "!Stop" },
        { name: "!forward", description: "Fast forward the track by specified seconds", usage: "!forward <seconds>" },
        { name: "!rewind", description: "Rewind the track by specified seconds", usage: "!rewind <seconds>" },
        { name: "!seek", description: "Seek to a specific timestamp in the song", usage: "!seek <mm:ss>" },
        { name: "!replay", description: "Replay the current track from the beginning", usage: "!replay" },
        { name: "!vol", description: "Check or change player volume", usage: "!vol <1-100>" },
        { name: "!volume", description: "Adjust player volume level", usage: "!volume <1-100>" },
        { name: "!np", description: "Display details of the currently playing song", usage: "!np" },
        { name: "!history", description: "Show recently played tracks history", usage: "!history" },
        { name: "!lyric", description: "Fetch lyrics for the current or specified song", usage: "!lyric [song name]" },
        { name: "!rec", description: "Get song recommendations based on current track", usage: "!rec" },
        { name: "!search", description: "Search for a song and choose from top results", usage: "!search <query>" },
        { name: "!QueueCommand", description: "Show the current server music queue list", usage: "!QueueCommand" },
        { name: "!stay247", description: "Toggle 24/7 mode to keep bot in VC permanently", usage: "!stay247" },
        { name: "!bassboost", description: "Toggle bassboost filter status", usage: "!bassboost" },
        { name: "!deepbass", description: "Apply an extra deep bass audio filter", usage: "!deepbass" },
        { name: "!superbass", description: "Apply maximum bass boost filter", usage: "!superbass" },
        { name: "!boost", description: "Apply general audio frequency boost", usage: "!boost" },
        { name: "!flat", description: "Reset audio equalizer to flat/normal status", usage: "!flat" },
        { name: "!soft", description: "Apply a soft and smooth audio filter", usage: "!soft" },
        { name: "!warm", description: "Apply a warm acoustic equalizer filter", usage: "!warm" },
        { name: "!metal", description: "Apply heavy metal equalizer filter settings", usage: "!metal" },
        { name: "!oldschool", description: "Apply retro oldschool filter settings", usage: "!oldschool" },
        { name: "!filter", description: "View or apply advanced audio filters", usage: "!filter <filter_name>" },
        { name: "!classical", description: "Apply classical music equalizer settings", usage: "!classical" },
        { name: "!electronic", description: "Apply electronic/EDM filter settings", usage: "!electronic" },
        { name: "!hiphop", description: "Apply hip-hop equalizer filter setup", usage: "!hiphop" },
        { name: "!jazz", description: "Apply smooth jazz audio equalizer settings", usage: "!jazz" },
        { name: "!pop", description: "Apply pop music enhancer filter", usage: "!pop" },
        { name: "!reggae", description: "Apply reggae audio style equalizer", usage: "!reggae" },
        { name: "!rock", description: "Apply rock music high-energy filter", usage: "!rock" },
        { name: "!reset", description: "Reset all active audio filters instantly", usage: "!reset" },
        { name: "!gaming", description: "Apply gaming audio enhancement equalizer", usage: "!gaming" },
        { name: "!nightcore", description: "Apply high-speed nightcore audio filter", usage: "!nightcore" },
        { name: "!vaporwave", description: "Apply slowed/reverbed vaporwave filter effect", usage: "!vaporwave" },
        { name: "!bright", description: "Apply bright high-frequency enhancer filter", usage: "!bright" },
        { name: "!treble", description: "Boost treble frequencies in audio", usage: "!treble" },
        { name: "!vocals", description: "Enhance vocals and dim background instrumentals", usage: "!vocals" },
        { name: "!ap", description: "Toggle autoplay mode for infinite music", usage: "!ap" },
        { name: "!playlist", description: "View or play custom master playlists", usage: "!playlist" },
        { name: "!create-pl", description: "Create a brand new empty personal playlist", usage: "!create-pl <name>" },
        { name: "!add2pl", description: "Add the current playing song into your playlist", usage: "!add2pl <playlist_name>" },
        { name: "!load-pl", description: "Load and play all tracks from a custom playlist", usage: "!load-pl <playlist_name>" },
        { name: "!my-playlists", description: "View a list of all your created playlists", usage: "!my-playlists" },
        { name: "!pl-info", description: "View details and tracks of a specific playlist", usage: "!pl-info <playlist_name>" },
        { name: "!pl-edit", description: "Edit details or rename your custom playlist", usage: "!pl-edit <playlist_name>" },
        { name: "!pl-remove", description: "Remove a track from your custom playlist", usage: "!pl-remove <playlist_name> <track_index>" },
        { name: "!del-playlists", description: "Delete an existing custom playlist permanently", usage: "!del-playlists <playlist_name>" },
        { name: "/filter", description: "filter commands.", usage: "/filter" },
        { name: "/queue", description: "Manage the music queue", usage: "/queue" },
        { name: "/music", description: "music commands.", usage: "/music" },
        { name: "/playlist", description: "Manage your custom playlists", usage: "/playlist" }
      ],
    },
    {
      name: "Utility",
      commands: [
        { name: "!serverinfo", description: "Display detailed server configuration and stats", usage: "!serverinfo" },
        { name: "!userinfo", description: "Display detailed user information and platform roles", usage: "!userinfo [user]" },
        { name: "!avatar", description: "Show user avatar in high definition size", usage: "!avatar [user]" },
        { name: "!banner", description: "Show user banner image if available", usage: "!banner [user]" },
        { name: "!serverbanner", description: "Show the current server banner layout picture", usage: "!serverbanner" },
        { name: "!servericon", description: "Show the current server icon logo", usage: "!servericon" },
        { name: "!roleinfo", description: "Display permissions and details of a server role", usage: "!roleinfo <role>" },
        { name: "!membercount", description: "Show precise real-time member count statistics", usage: "!membercount" },
        { name: "!boostcount", description: "Show total number of server boosts received", usage: "!boostcount" },
        { name: "!channelcount", description: "Show text, voice, and category counts of server", usage: "!channelcount" },
        { name: "!emojilist", description: "List all custom emojis uploaded to the server", usage: "!emojilist" },
        { name: "!firstmessage", description: "Get a link to the absolute first message of a channel", usage: "!firstmessage" },
        { name: "!guildbanner", description: "Show the official server guild splash banner", usage: "!guildbanner" },
        { name: "!stats", description: "Show comprehensive performance stats of AstraX bot", usage: "!stats" },
        { name: "!uptime", description: "Show continuous runtime uptime clock of the bot", usage: "!uptime" },
        { name: "!ping", description: "Check current bot latency and websocket connection response", usage: "!ping" },
        { name: "!help", description: "Browse command categories and detailed guide information", usage: "!help [command]" },
        { name: "!invite", description: "Get the bot's official invite link for servers", usage: "!invite" },
        { name: "!support", description: "Get invite link to the official support server hub", usage: "!support" },
        { name: "!team", description: "View information about the development core team", usage: "!team" },
        { name: "!tos", description: "View the bot's Terms of Service guidelines", usage: "!tos" },
        { name: "!feedback", description: "Send feedback notes directly to bot developers", usage: "!feedback <text>" },
        { name: "!report", description: "Report bot bugs or issues to tech support", usage: "!report <text>" },
        { name: "!suggest", description: "Suggest new feature concepts or module changes", usage: "!suggest <text>" },
        { name: "!poll", description: "Create a beautifully styled interactive reaction poll", usage: "!poll <question>" },
        { name: "!timer", description: "Set a countdown timer tracker with message alert", usage: "!timer <duration>" },
        { name: "!translate", description: "Translate text content into English or other target languages", usage: "!translate <language> <text>" },
        { name: "!upload", description: "Upload files or assets securely to cloud servers", usage: "!upload [file]" },
        { name: "!remind", description: "Set a personal reminder for future times", usage: "!remind <time> <text>" },
        { name: "!remindinfo", description: "Check your active pending reminders list", usage: "!remindinfo" },
        { name: "!remindreset", description: "Clear or reset all your active reminders", usage: "!remindreset" },
        { name: "!role", description: "Give, remove or manage user roles configurations", usage: "!role <user> <role>" },
        { name: "!setup", description: "Master command to launch setup wizards for features", usage: "!setup <feature>" },
        { name: "!steal", description: "Steal an emoji from another server using its URL/text", usage: "!steal <emoji_custom>" },
        { name: "!stealsticker", description: "Steal a custom sticker into your server assets", usage: "!stealsticker" },
        { name: "!nick", description: "Change a member's custom server nickname alias", usage: "!nick <user> <new_name>" },
        { name: "!autonickname", description: "Configure automated nickname tags for incoming users", usage: "!autonickname <tag>" },
        { name: "!sticky", description: "Manage sticky messages pinned at bottom of chat", usage: "!sticky <message>" },
        { name: "!afk", description: "Set your status to AFK with a custom reason notice", usage: "!afk [reason]" },
        { name: "!snipe", description: "Retrieve the most recently deleted message text in channel", usage: "!snipe" },
        { name: "!Prefix", description: "Check or change the bot's custom server text prefix", usage: "!Prefix [new_prefix]" },
        { name: "!userprefix", description: "Configure a unique custom prefix for your own use", usage: "!userprefix <prefix>" },
        { name: "!welcome", description: "Launch configuration engine for welcome layouts", usage: "!welcome" },
        { name: "!welcomechannel", description: "Set text channel for welcoming new arrivals", usage: "!welcomechannel <#channel>" },
        { name: "!welcomemessage", description: "Set custom greeting message for new members", usage: "!welcomemessage <text>" },
        { name: "!welcomereset", description: "Reset welcome modules back to factory settings", usage: "!welcomereset" },
        { name: "!welcometest", description: "Trigger a mock test welcome message card in chat", usage: "!welcometest" },
        { name: "!greet", description: "Configure short greet message styles", usage: "!greet" },
        { name: "!left", description: "Configure departure announcement styles for left users", usage: "!left" },
        { name: "!chatbot", description: "Configure or activate the AI Chatbot module channel", usage: "!chatbot <#channel>" },
        { name: "!counting", description: "Configure an automatic numbers counting game channel", usage: "!counting <#channel>" },
        { name: "!guessnumber", description: "Manage a fun guess the hidden number mini game module", usage: "!guessnumber" },
        { name: "!backup", description: "Create, load or manage cloud server configuration backups", usage: "!backup <create/load>" },
        { name: "!npt", description: "Toggle no-prefix tracking for privileged users", usage: "!npt" },
        { name: "!pfp-drop", description: "Configure automatic PFP/banner profile gallery drops", usage: "!pfp-drop" },
        { name: "!pfp", description: "Get random profile pictures from community galleries", usage: "!pfp [category]" },
        { name: "!serverprofile", description: "Customize the bot's server profile avatar/nick (Luxury)", usage: "!serverprofile" },
        { name: "!autoresponder", description: "Set up automatic text replies to triggers", usage: "!autoresponder" },
        { name: "!autoreact", description: "Set up automatic reactions for channel uploads", usage: "!autoreact" },
        { name: "!jointocreate", description: "Launch setup for Join to Create temporary VC generation", usage: "!jointocreate" },
        { name: "!leveling", description: "Configure and toggle the text XP leveling module system", usage: "!leveling" },
        { name: "!autologs", description: "Automatically create and configure all vital log channels", usage: "!autologs" },
        { name: "!channellog", description: "Configure channel dedicated to logging channel alterations", usage: "!channellog <#channel>" },
        { name: "!logall", description: "Direct all system events logs into one specific channel", usage: "!logall <#channel>" },
        { name: "!logs", description: "Configure comprehensive custom server logging arrays", usage: "!logs" },
        { name: "!memberlog", description: "Configure specific logging channel for member leaves/joins", usage: "!memberlog <#channel>" },
        { name: "!messagelog", description: "Configure advanced log tracking for message edits/deletions", usage: "!messagelog <#channel>" },
        { name: "!modlog", description: "Configure logs channel for core moderator tracking actions", usage: "!modlog <#channel>" },
        { name: "!resetlogs", description: "Wipe clean all current logging assignments configurations", usage: "!resetlogs" },
        { name: "!rolelog", description: "Configure logs for server role updates/creations", usage: "!rolelog <#channel>" },
        { name: "!showlogs", description: "View the comprehensive list of current log channels links", usage: "!showlogs" },
        { name: "!vclogs", description: "Configure logging tracking engine for voice channels updates", usage: "!vclogs <#channel>" },
        { name: "!AutoroleCommand", description: "Configure setup for role assignments on member join", usage: "!AutoroleCommand" },
        { name: "!autorole", description: "Manage automated role distribution rules", usage: "!autorole" },
        { name: "!VerificationCommand", description: "Launch setup for captcha/button verification system", usage: "!VerificationCommand" },
        { name: "!ReactionRoleCommand", description: "Configure complex custom reaction roles panels", usage: "!ReactionRoleCommand" },
        { name: "!embed", description: "Launch visual builder tool to write customized rich embeds", usage: "!embed" },
        { name: "!addinvites", description: "Manually add promotional invites to a member balance", usage: "!addinvites <user> <count>" },
        { name: "!invitecodes", description: "View active tracker invite links belonging to server", usage: "!invitecodes" },
        { name: "!inviteleaderboard", description: "Display top users leading in server invites statistics", usage: "!inviteleaderboard" },
        { name: "!invitemessage", description: "Customize tracking messages announced upon user invites", usage: "!invitemessage <text>" },
        { name: "!inviter", description: "Identify which user invited a specific member", usage: "!inviter <user>" },
        { name: "!inviterank", description: "Check current milestones rank achieved by your invites", usage: "!inviterank" },
        { name: "!inviteranks", description: "View full set of invite role progression milestones setup", usage: "!inviteranks" },
        { name: "!invites-master", description: "Open control configuration terminal for invite trackers", usage: "!invites-master" },
        { name: "!invites", description: "Check your complete custom server invitation statistics summary", usage: "!invites [user]" },
        { name: "!invitesimport", description: "Import classic native Discord invite metrics to tracker logs", usage: "!invitesimport" },
        { name: "!invitetracker", description: "Toggle status control over invite tracker modules", usage: "!invitetracker <on/off>" },
        { name: "!resetinvites", description: "Reset invite counters database statistics for whole server", usage: "!resetinvites" },
        { name: "!tempvc", description: "Configure setup rules tracking auto temporary voice hubs", usage: "!tempvc" },
        { name: "!vcdeafen", description: "Deafen an active member within a voice channel", usage: "!vcdeafen <user>" },
        { name: "!vcdeafenall", description: "Deafen every single member inside current voice layout", usage: "!vcdeafenall" },
        { name: "!vckick", description: "Disconnect a user instantly from voice channels servers", usage: "!vckick <user>" },
        { name: "!vckickall", description: "Kick out every connected user inside active voice hub", usage: "!vckickall" },
        { name: "!vclist", description: "List all channels tracking ongoing voice conversations statistics", usage: "!vclist" },
        { name: "!vcmoveall", description: "Mass move all voice users from one hub to another channel", usage: "!vcmoveall <from> <to>" },
        { name: "!vcmute", description: "Server mute an active user inside voice rooms", usage: "!vcmute <user>" },
        { name: "!vcmuteall", description: "Mute all users presently connected to voice audio stream", usage: "!vcmuteall" },
        { name: "!vcpull", description: "Pull a member from another voice hub into your active one", usage: "!vcpull <user>" },
        { name: "!vcpush", description: "Push an active member into another designated voice layout", usage: "!vcpush <user> <channel>" },
        { name: "!vcrole", description: "Assign a dynamic temporary role active only while in VC", usage: "!vcrole <role>" },
        { name: "!vcundeafen", description: "Undeafen a voice muted member in the conversation", usage: "!vcundeafen <user>" },
        { name: "!vcundeafenall", description: "Undeafen all connected voice users simultaneously", usage: "!vcundeafenall" },
        { name: "!vcunmute", description: "Remove voice server mute from an active user", usage: "!vcunmute <user>" },
        { name: "!vcunmuteall", description: "Unmute all server voice participants instantly", usage: "!vcunmuteall" },
        { name: "/ping", description: "Check bot latency and connection status", usage: "/ping" },
        { name: "/botinfo", description: "Get detailed information about the bot.", usage: "/botinfo" },
        { name: "/feedback", description: "Send feedback about the bot to the developers.", usage: "/feedback" },
        { name: "/help", description: "Browse command categories and command details", usage: "/help" },
        { name: "/invite", description: "Get the bot's invite link to add it to your server.", usage: "/invite" },
        { name: "/report", description: "Report bugs or issues with the bot to the developers.", usage: "/report" },
        { name: "/suggest", description: "Suggest new features or improvements for the bot.", usage: "/suggest" },
        { name: "/support", description: "Get support and help with the bot.", usage: "/support" },
        { name: "/teaminfo", description: "Get information about the development team.", usage: "/teaminfo" },
        { name: "/tos", description: "View the bot's Terms of Service and usage guidelines.", usage: "/tos" },
        { name: "/invites", description: "Unified invite management system", usage: "/invites" },
        { name: "/role", description: "Manage roles for users", usage: "/role" },
        { name: "/ticket", description: "Unified ticket management system", usage: "/ticket" },
        { name: "/embed", description: "Open the interactive embed builder", usage: "/embed" },
        { name: "/autorole", description: "Manage autoroles for new members", usage: "/autorole" },
        { name: "/verification", description: "Manage verification system", usage: "/verification" },
        { name: "/setup", description: "Master setup command for bot features.", usage: "/setup" },
        { name: "/reactionrole", description: "Manage reaction roles", usage: "/reactionrole" },
        { name: "/boost", description: "Configure server boost notifications", usage: "/boost" },
        { name: "/chatbot", description: "Configure the AI Chatbot", usage: "/chatbot" },
        { name: "/left", description: "Configure leave messages", usage: "/left" },
        { name: "/greet", description: "Configure greet messages", usage: "/greet" },
        { name: "/pfp-drop", description: "Configure automatic PFP/banner drops", usage: "/pfp-drop" },
        { name: "/sticky", description: "Manage sticky messages", usage: "/sticky" },
        { name: "/welcome", description: "Configure welcome system", usage: "/welcome" },
        { name: "/utility", description: "utility commands.", usage: "/utility" },
        { name: "/bump", description: "Configure bump reminder settings", usage: "/bump" },
        { name: "/ignore", description: "Configure channels or roles for the bot to ignore", usage: "/ignore" },
        { name: "/media", description: "Configure media-only channels and whitelists", usage: "/media" },
        { name: "/counting", description: "Configure counting channel", usage: "/counting" },
        { name: "/guessnumber", description: "Manage a guess number game", usage: "/guessnumber" },
        { name: "/autonickname", description: "Configure auto-nickname tag", usage: "/autonickname" },
        { name: "/autologs", description: "Automatically create and configure all log channels.", usage: "/autologs" },
        { name: "/channellog", description: "Configure the channel for channel-related logs.", usage: "/channellog" },
        { name: "/showlogs", description: "View current logging configuration.", usage: "/showlogs" },
        { name: "/memberlog", description: "Configure the channel for member-related logs.", usage: "/memberlog" },
        { name: "/messagelog", description: "Configure the channel for message-related logs.", usage: "/messagelog" },
        { name: "/modlog", description: "Configure the channel for moderation-related logs.", usage: "/modlog" },
        { name: "/rolelog", description: "Configure the channel for role-related logs.", usage: "/rolelog" },
        { name: "/vclogs", description: "Configure the channel for voice-related logs.", usage: "/vclogs" },
        { name: "/logall", description: "Set one channel for all types of logs.", usage: "/logall" },
        { name: "/resetlogs", description: "Reset all logging configuration for this server.", usage: "/resetlogs" },
        { name: "/backup", description: "Create and manage server backups", usage: "/backup" },
        { name: "/pp", description: "View the bot's Privacy Policy and data handling practices.", usage: "/pp" },
        { name: "/logs", description: "Configure server logging system.", usage: "/logs" },
        { name: "/vc", description: "vc commands.", usage: "/vc" },
        { name: "/tempvc", description: "Setup and manage temporary voice channels", usage: "/tempvc" }
      ],
    },
    {
      name: "Fun",
      commands: [
        { name: "!meme", description: "Get a random fresh meme asset from Reddit channels", usage: "!meme" },
        { name: "!action", description: "Perform an expression action (hug, slap, etc) on someone", usage: "!action <type> <user>" },
        { name: "!dare", description: "Receive a random dare challenge statement", usage: "!dare" },
        { name: "!truth", description: "Receive an interactive random truth question query", usage: "!truth" },
        { name: "!hack", description: "Execute a completely simulated joke hack on a targeted member", usage: "!hack <user>" },
        { name: "!howdumb", description: "Calculate joke dumbness percentage metric rating", usage: "!howdumb [user]" },
        { name: "!howgay", description: "Calculate joke compatibility gay percentage radar stat", usage: "!howgay [user]" },
        { name: "!kill", description: "Generate a funny automated text scenario killing a user", usage: "!kill <user>" },
        { name: "!lick", description: "Perform a funny roleplay licking action animation text", usage: "!lick <user>" },
        { name: "!nitro", description: "Generate a fake mock Nitro gift link asset item", usage: "!nitro" },
        { name: "!pickup", description: "Get a cheesy unique pick-up line quote asset text", usage: "!pickup [user]" },
        { name: "!simprate", description: "Calculate joke simp meter alignment percentage rank", usage: "!simprate [user]" },
        { name: "!texttoemoji", description: "Convert standard chat text letters directly into big emojis", usage: "!texttoemoji <text>" },
        { name: "!animes", description: "Fetch random aesthetic or popular anime wallpapers assets", usage: "!animes" },
        { name: "!banners", description: "Get randomized aesthetic banner art profile designs", usage: "!banners" },
        { name: "!boys", description: "Get random aesthetic boy pfp avatars suggestions", usage: "!boys" },
        { name: "!girls", description: "Get random aesthetic girl pfp avatars suggestions", usage: "!girls" },
        { name: "!couples", description: "Get matching layout matching couple icons pfps pairs", usage: "!couples" },
        { name: "!pfp", description: "Request random standard community matching avatars", usage: "!pfp" },
        { name: "!adopt", description: "Adopt an active server member into your virtual family trees", usage: "!adopt <user>" },
        { name: "!disown", description: "Remove a child user from your global family profiles", usage: "!disown <user>" },
        { name: "!divorce", description: "Formally terminate a marriage relationship status with a user", usage: "!divorce <user>" },
        { name: "!family", description: "View a visual graph layout structure of your tree family", usage: "!family" },
        { name: "!leave", description: "Walk away from your current linked parents virtual home setup", usage: "!leave" },
        { name: "!marry", description: "Propose a formal virtual marriage alliance string to a user", usage: "!marry <user>" },
        { name: "!ship", description: "Calculate definitive love percentage bond between two items", usage: "!ship <user1> [user2]" },
        { name: "!quote", description: "Generate a premium styled quote canvas graphic design text", usage: "!quote <user> <text>" },
        { name: "!social", description: "Manage global user relationship parameters", usage: "!social" },
        { name: "!userphone", description: "Join global phone channels chat room streams randomly", usage: "!userphone" },
        { name: "!coinflip", description: "Flip an independent economic coin for 50/50 gambling chances", usage: "!coinflip [amount]" },
        { name: "!dice", description: "Roll a standard dice layout and wager betting coins", usage: "!dice <number> [amount]" },
        { name: "!invest", description: "Invest server coins balance tokens into high-risk market stocks", usage: "!invest <company> <amount>" },
        { name: "!roulette", description: "Play classical roulette casino layout red/black betting streams", usage: "!roulette <color> <amount>" },
        { name: "!slots", description: "Spin a 3-row slot machine layout row for economy rewards", usage: "!slots <amount>" },
        { name: "!balance", description: "Check current wallet bank tokens cash data balance", usage: "!balance [user]" },
        { name: "!daily", description: "Claim a reward daily token bonus payout package asset", usage: "!daily" },
        { name: "!profile", description: "Show complete multi-tier summary interactive layout dashboard", usage: "!profile" },
        { name: "!beg", description: "Beg the bot engine for casual emergency currency handouts", usage: "!beg" },
        { name: "!work", description: "Work standard regular shift hours to collect economy tokens salary", usage: "!work" },
        { name: "!shop", description: "Open market shop catalog matrix to trade server items assets", usage: "!shop" },
        { name: "!economy", description: "Open central menu interface dashboard for server economy tracking", usage: "!economy" },
        { name: "!blacksmith", description: "Craft, repair or upgrade weapon items tool arrays", usage: "!blacksmith" },
        { name: "!chop", description: "Chop lumber wood logs in virtual maps files to gain items", usage: "!chop" },
        { name: "!code", description: "Write virtual software programs inside bot jobs systems to earn coins", usage: "!code" },
        { name: "!cook", description: "Cook ingredients recipes items assets to sustain health pools", usage: "!cook" },
        { name: "!courier", description: "Deliver delivery packages roles jobs tasks to claim payouts", usage: "!courier" },
        { name: "!craft", description: "Craft raw components together to make valuable store items", usage: "!craft <item>" },
        { name: "!crime", description: "Attempt high-risk illegal digital heists to steal large coin pools", usage: "!crime" },
        { name: "!explore", description: "Explore mysterious territory maps coordinates for hidden assets loot", usage: "!explore" },
        { name: "!farm", description: "Plant, grow and harvest agricultural farming crops items rows", usage: "!farm" },
        { name: "!fish", description: "Fish inside regional water bodies streams to capture seafood items", usage: "!fish" },
        { name: "!garden", description: "Tend custom flower botanical greenhouse gardens grids layouts", usage: "!garden" },
        { name: "!hunt", description: "Hunt wildlife game creatures assets in woods maps to sell loot", usage: "!hunt" },
        { name: "!mine", description: "Mine rock caves depths layers to extract high value diamond ores", usage: "!mine" },
        { name: "!patrol", description: "Guard regional border city zones checkpoints to earn security bounty bonuses", usage: "!patrol" },
        { name: "!perform", description: "Perform stage talents theater songs shows to get crowd coin donations", usage: "!perform" },
        { name: "!pilot", description: "Fly flight transport routes pathways to fetch cargo transport salaries", usage: "!pilot" },
        { name: "!raid", description: "Organize group raiding combat sessions layouts against boss targets", usage: "!raid" },
        { name: "!repair", description: "Repair broken dynamic toolkit mechanics item files setups", usage: "!repair <item>" },
        { name: "!research", description: "Research laboratory technology tech files blueprints node trees", usage: "!research" },
        { name: "!salvage", description: "Salvage destroyed machinery scrap metal piles to recover components", usage: "!salvage" },
        { name: "!scavenge", description: "Scavenge abandoned city ruins trash zones to discover random things", usage: "!scavenge" },
        { name: "!stream", description: "Launch virtual streaming video channel content modules to collect subs tips", usage: "!stream" },
        { name: "!sweep", description: "Sweep cleaning chores inside base camps facilities to secure allowances", usage: "!sweep" },
        { name: "!theft", description: "Pickpocket coin balances from targeted users files tracking directly", usage: "!theft <user>" },
        { name: "!tutor", description: "Teach educational academy classes files coaching courses to generate income", usage: "!tutor" },
        { name: "!economyAdmin", description: "Master admin toolkit to set, clear or grant money values", usage: "!economyAdmin" },
        { name: "!giveaway", description: "Initiate master terminal setup for interactive server raffles", usage: "!giveaway" },
        { name: "!gstart", description: "Launch a new automated giveaway flash layout draw in channel", usage: "!gstart <time> <winners> <prize>" },
        { name: "!gpause", description: "Pause a currently active running countdown server giveaway draw", usage: "!gpause <message_id>" },
        { name: "!gresume", description: "Resume a paused ongoing raffle draw timer tracking clock", usage: "!gresume <message_id>" },
        { name: "!gedit", description: "Modify timer metrics or prize string labels of an active giveaway", usage: "!gedit <message_id>" },
        { name: "!end", description: "Stop giveaway timer instantly and enforce immediate random winner selection", usage: "!gend <message_id>" },
        { name: "!greroll", description: "Draw a clean new random alternative winner string from past entry pools", usage: "!greroll <message_id>" },
        { name: "!gban", description: "Ban an exploit user from logging entries into server giveaway arrays", usage: "!gban <user>" },
        { name: "!gunban", description: "Restore user eligibility permissions to rejoin server giveaway tasks", usage: "!gunban <user>" },
        { name: "!cute", description: "Fetch adorable animal or scenery picture frames arrays from database", usage: "!cute" },
        { name: "!imagine", description: "Generate beautiful AI art conceptual picture frames layout responses", usage: "!imagine <prompt>" },
        { name: "!intelligence", description: "Calculate joke IQ mental rating metrics scoring points map", usage: "!intelligence [user]" },
        { name: "!wouldyourather", description: "Serve an interactive choose-one choice text question poll template", usage: "!wouldyourather" },
        { name: "!addpremium", description: "Manually bind premium status tier privilege onto a specific server", usage: "!addpremium <server_id>" },
        { name: "!premium", description: "Check status details tracking your global bot premium tier benefits", usage: "!premium" },
        { name: "!listprem", description: "Display list tracking all servers assigned with active premium assets", usage: "!listprem" },
        { name: "!removepremium", description: "Revoke premium license configurations access away from a layout target", usage: "!removepremium <server_id>" },
        { name: "!updatepremium", description: "Refresh or modify authorization keys logs for premium active profiles", usage: "!updatepremium" },
        { name: "!blacklistserver", description: "Ban a whole entire discord server framework from deploying AstraX", usage: "!blacklistserver <server_id>" },
        { name: "!unblacklistserver", description: "Lift restriction bans away from an absolute server structure layout", usage: "!unblacklistserver <server_id>" },
        { name: "!blacklistuser", description: "Ban a dangerous user completely from issuing any bot commands calls", usage: "!blacklistuser <user_id>" },
        { name: "!unblacklistuser", description: "Lift global restrictions blockades off a previously blacklisted individual", usage: "!unblacklistuser <user_id>" },
        { name: "!blacklist", description: "Open core administrative tracking layout dashboard tracking server bans arrays", usage: "!blacklist" },
        { name: "!globalban", description: "Enforce an un-bypasable global ban cross network structures against users", usage: "!globalban <user_id>" },
        { name: "!botset", description: "Access developer terminal control nodes over core bot functions", usage: "!botset" },
        { name: "!getuprestart", description: "Fetch system diagnostics metrics data before running safe reboot tasks", usage: "!getuprestart" },
        { name: "!leaveserver", description: "Force the bot code framework to leave a specific target server location", usage: "!leaveserver <server_id>" },
        { name: "!luxury", description: "Manage extreme luxury tier configurations exclusive server layout tools", usage: "!luxury" },
        { name: "!node", description: "Check connection metrics and system loads of core host audio nodes", usage: "!node" },
        { name: "!noprefix", description: "Grant a user access to run command arrays without entering prefixes", usage: "!noprefix add <user>" },
        { name: "!ownernoprefix", description: "Developer exclusive toggle for global no-prefix permissions override", usage: "!ownernoprefix" },
        { name: "!releasedball", description: "Wipe memory tracking logs and release locked shards databases records", usage: "!releasedball" },
        { name: "!reload", description: "Hot-reload a single specified system command code file architecture", usage: "!reload <command_name>" },
        { name: "!reloadall", description: "Hot-reload every single module package code file across framework", usage: "!reloadall" },
        { name: "!reloadcmd", description: "Target and reload specific backend route configuration files files", usage: "!reloadcmd <command_name>" },
        { name: "!rl", description: "Fast short macro route to hot-reload selected single modules paths", usage: "!rl <command_name>" },
        { name: "!restart", description: "Enforce sudden clean system safe restart operation over source process", usage: "!restart" },
        { name: "!say", description: "Broadcast written announcement strings through the bot directly in chat", usage: "!say <text>" },
        { name: "!serverinvite", description: "Generate explicit support platform server access invitation strings tracking links", usage: "!serverinvite <server_id>" },
        { name: "!serverlist", description: "Display comprehensive text dashboard tracking all active server installations", usage: "!serverlist" },
        { name: "!shard", description: "Check performance logs metrics for a specific computing shard unit", usage: "!shard <id>" },
        { name: "!shards", description: "Display general operational grid summary tracking all running cluster shards", usage: "!shards" },
        { name: "!updateslash", description: "Force deploy updated global Slash interaction commands directly onto Discord API", usage: "!updateslash" },
        { name: "!extraowner", description: "Assign trusted co-developers full access to owner command layers", usage: "!extraowner <user>" },
        { name: "!mainrole", description: "Set or manage high priority primary system authority roles", usage: "!mainrole" },
        { name: "!nightmode", description: "Lock down specific features during designated server quiet times", usage: "!nightmode" },
        { name: "!panicmode", description: "Instantly lock down all bot interactions server-wide if an exploit is detected", usage: "!panicmode" },
        { name: "!whitelist", description: "Add a member to the immune anti-nuke system safe configuration bypass list", usage: "!whitelist <user>" },
        { name: "!unwhitelist", description: "Remove a member from the anti-nuke safe pass privileges configurations", usage: "!unwhitelist <user>" },
        { name: "!whitelisted", description: "Display list tracking all users immune to security modules monitoring", usage: "!whitelisted" },
        { name: "!whitelistreset", description: "Wipe clean all members registered under anti-nuke safety bypass configurations", usage: "!whitelistreset" },
        { name: "!Prem", description: "Configure system modules tracking developer premium key distribution parameters", usage: "!Prem" },
        { name: "!bitzxier", description: "Internal pipeline control panel macro reserved for main developers logging setups", usage: "!bitzxier" },
        { name: "!eval", description: "Execute direct arbitrary JavaScript code strings directly inside process runtime environment", usage: "!eval <code>" },
        { name: "!execute", description: "Run system terminal shell commands direct from console logging pipeline", usage: "!execute <command>" },
        { name: "!maintancemode", description: "Toggle overall global maintenance locks preventing user query processing operations", usage: "!maintancemode" },
        { name: "!panelsetup", description: "Launch structural configuration engine for support tickets panel nodes", usage: "!panelsetup" },
        { name: "!panelsend", description: "Dispatch fully configured ticket buttons embeds panels into chat logs channels", usage: "!panelsend <#channel>" },
        { name: "!ticket", description: "Open custom customer support channel tracking pipeline windows", usage: "!ticket" },
        { name: "!ticket-master", description: "Access central backend dashboard parameters governing tickets arrays routing setups", usage: "!ticket-master" },
        { name: "!claim", description: "Claim ownership over an opened client support ticket channel file", usage: "!claim" },
        { name: "!close", description: "Close down a resolved client help desk support ticket instance channel", usage: "!close" },
        { name: "!add", description: "Add a specific extra member into an existing support ticket conversation channel", usage: "!add <user>" },
        { name: "!delete", description: "Instantly delete ticket channel completely and wipe trace logs data", usage: "!delete" },
        { name: "!rename", description: "Change text label alias tracking an ongoing ticket room window", usage: "!rename <new_name>" },
        { name: "!retick", description: "Reopen a previously closed ticket session window tracking dashboard", usage: "!retick" },
        { name: "!reviewsetup", description: "Configure automated user satisfaction feedback loops questions for closed tickets", usage: "!reviewsetup" },
        { name: "!transcript", description: "Generate backup file tracking conversation logs of a ticket room", usage: "!transcript" },
        { name: "!fuckticket", description: "Emergency fast force close tool to override blocked or stuck support loops", usage: "!fuckticket" },
        { name: "!reaction", description: "Configure specialized custom reaction triggers responding to specified inputs", usage: "!reaction" },
        { name: "/say", description: "Make the bot say something in a channel", usage: "/say" },
        { name: "/economy", description: "Manage your economy and purchases", usage: "/economy" },
        { name: "/rewards", description: "Configure role rewards", usage: "/rewards" },
        { name: "/pfp", description: "Get random profile pictures", usage: "/pfp" },
        { name: "/serverprofile", description: "Customize the bot's appearance in this server (Luxury only)", usage: "/serverprofile" },
        { name: "/social", description: "Social and relationship commands", usage: "/social" },
        { name: "/giveaway", description: "Manage giveaways in the server", usage: "/giveaway" },
        { name: "/level", description: "Leveling system commands", usage: "/level" },
        { name: "/autoresponder", description: "Set up automatic responses to specific triggers", usage: "/autoresponder" },
        { name: "/autoreact", description: "Set up automatic reactions in a channel", usage: "/autoreact" },
        { name: "/adopt", description: "Adopt someone into your family", usage: "/adopt" },
        { name: "/disown", description: "Remove someone from your children list", usage: "/disown" },
        { name: "/divorce", description: "Divorce your current spouse", usage: "/divorce" },
        { name: "/family", description: "View your family tree in a simple format", usage: "/family" },
        { name: "/quote", description: "Generate a premium quote image from text", usage: "/quote" },
        { name: "/ship", description: "Ship two people together", usage: "/ship" },
        { name: "/userphone", description: "Call random users globally and optionally hide your identity.", usage: "/userphone" },
        { name: "/leave", description: "Leave your parents' family", usage: "/leave" },
        { name: "/marry", description: "Propose marriage to someone special", usage: "/marry" },
        { name: "/whitelisted", description: "Show AntiNuke whitelist users", usage: "/whitelisted" },
        { name: "/unwhitelist", description: "Remove user from AntiNuke whitelist", usage: "/unwhitelist" },
        { name: "/whitelist", description: "Add user to AntiNuke whitelist", usage: "/whitelist" },
        { name: "/whitelistreset", description: "Clear all users from AntiNuke whitelist", usage: "/whitelistreset" },
        { name: "/invest", description: "Invest in high-risk stocks", usage: "/invest" },
        { name: "/slots", description: "Spin the slot machine", usage: "/slots" },
        { name: "/balance", description: "Check your current coin balance", usage: "/balance" },
        { name: "/daily", description: "Claim your daily gift", usage: "/daily" },
        { name: "/roulette", description: "Play roulette and bet on red or black", usage: "/roulette" },
        { name: "/dice", description: "Roll a dice and bet on a number", usage: "/dice" },
        { name: "/profile", description: "Show your full account details in an interactive menu", usage: "/profile" },
        { name: "/coinflip", description: "Flip a coin for a 50/50 chance to win", usage: "/coinflip" },
        { name: "/gban", description: "Ban a user from participating in giveaways", usage: "/gban" },
        { name: "/gend", description: "End a giveaway immediately", usage: "/gend" },
        { name: "/gpause", description: "Pause an active giveaway", usage: "/gpause" },
        { name: "/greroll", description: "Reroll a giveaway winner", usage: "/greroll" },
        { name: "/gresume", description: "Resume a paused giveaway", usage: "/gresume" },
        { name: "/bump", description: "Configure bump reminder settings", usage: "/bump" },
        { name: "/media", description: "Configure media-only channels and whitelists", usage: "/media" },
        { name: "/action", description: "Perform a fun action on someone (SFW)", usage: "/action" },
        { name: "/gedit", description: "Edit an existing giveaway", usage: "/gedit" },
        { name: "/gstart", description: "Start a new giveaway", usage: "/gstart" },
        { name: "/gunban", description: "Unban a user from giveaways", usage: "/gunban" },
        { name: "/texttoemoji", description: "Convert text to emoji letters", usage: "/texttoemoji" },
        { name: "/truth", description: "Get a random truth question", usage: "/truth" }
      ],
    },
  ],
  team: [
    {
      name: "AeroX 1",
      role: "Founder & Lead Developer",
      bio: "Architects the core. Loves clean code and 3am refactors.",
      avatar: prayagAvatar,
      socials: { github: "#", twitter: "#" },
    },
    {
      name: "AeroX 2",
      role: "Product Designer",
      bio: "Crafts the pixels you fall in love with.",
      avatar: "",
      socials: { github: "#", twitter: "#" },
    },
  ],

  faqs: [
    {
      q: "Is Aerox free to use?",
      a: "Yes, all core features are completely free. We offer an optional Premium tier for advanced music quality.",
    },
    {
      q: "How do I add AstraX to my server?",
      a: "Click the Invite button anywhere on the site, authorize the bot and you are ready.",
    },
    {
      q: "Does AstraX store my messages?",
      a: "No. We only store configuration data essential for commands.",
    },
  ],

  contact: {
    email: "xyz@gmail.com",
    discord: "https://discord.gg/aerox",
    github: "https://github.com/AeroXDevs",
    twitter: "https://twitter.com/nebula_bot",
  },

  socials: [
    { icon: Github, href: "#", label: "GitHub" },
    { icon: Twitter, href: "#", label: "Twitter" },
    { icon: Mail, href: "xyz@gmail.com", label: "Email" },
  ],

  privacy: {
    lastUpdated: "April 18 2026",
    sections: [
      {
        title: "Information We Collect",
        body: "We collect minimal data required for the bot to function: server IDs, channel IDs, role IDs.",
      },
    ],
  },

  terms: {
    sections: [
      {
        title: "Acceptable Use",
        body: "By using Nebula, you agree not to abuse the service.",
      },
    ],
  },
};

export type SiteConfig = typeof siteConfig;
